modLoader="javafml" #mandatory
loaderVersion="[47,)"

license="CC-BY-NC-4.0"

[[mods]]
modId="matowos_invisible_armor"
version="1.7.1+1.20-1.20.1"
displayName="Matowo's Invisible Armor"

issueTrackerURL="https://github.com/Mxttosierrv/matowos-invisible-armor/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/matowos-invisible-armor"
logoFile="../assets/matowos_invisible_armor/icon.png"

authors="Matowo"
description="Show off your skin!"

[[dependencies.matowos_invisible_armor]]
modId="forge"
mandatory=true
versionRange="[45,)"
ordering="NONE"
side="BOTH"

[[dependencies.matowos_invisible_armor]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "matowos_invisible_armor.mixins.json"